<?php

// scoper-autoload.php @generated by PhpScoper

$loader = (static function () {
    // Backup the autoloaded Composer files
    $existingComposerAutoloadFiles = $GLOBALS['__composer_autoload_files'] ?? [];

    $loader = require_once __DIR__.'/autoload.php';
    // Ensure InstalledVersions is available
    $installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
    if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;

    // Restore the backup and ensure the excluded files are properly marked as loaded
    $GLOBALS['__composer_autoload_files'] = \array_merge(
        $existingComposerAutoloadFiles,
        \array_fill_keys([], true)
    );

    return $loader;
})();

// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
if (!function_exists('humbug_phpscoper_expose_class')) {
    function humbug_phpscoper_expose_class($exposed, $prefixed) {
        if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
            spl_autoload_call($prefixed);
        }
    }
}
humbug_phpscoper_expose_class('ComposerAutoloaderInit5f1553fcb3bba055e03a6786d88fc82a', 'OtomatiesCoreVendor\ComposerAutoloaderInit5f1553fcb3bba055e03a6786d88fc82a');
humbug_phpscoper_expose_class('SQLite3Exception', 'OtomatiesCoreVendor\SQLite3Exception');
humbug_phpscoper_expose_class('DateError', 'OtomatiesCoreVendor\DateError');
humbug_phpscoper_expose_class('Override', 'OtomatiesCoreVendor\Override');
humbug_phpscoper_expose_class('DateException', 'OtomatiesCoreVendor\DateException');
humbug_phpscoper_expose_class('DateInvalidOperationException', 'OtomatiesCoreVendor\DateInvalidOperationException');
humbug_phpscoper_expose_class('DateObjectError', 'OtomatiesCoreVendor\DateObjectError');
humbug_phpscoper_expose_class('DateMalformedPeriodStringException', 'OtomatiesCoreVendor\DateMalformedPeriodStringException');
humbug_phpscoper_expose_class('DateMalformedStringException', 'OtomatiesCoreVendor\DateMalformedStringException');
humbug_phpscoper_expose_class('DateRangeError', 'OtomatiesCoreVendor\DateRangeError');
humbug_phpscoper_expose_class('DateInvalidTimeZoneException', 'OtomatiesCoreVendor\DateInvalidTimeZoneException');
humbug_phpscoper_expose_class('DateMalformedIntervalStringException', 'OtomatiesCoreVendor\DateMalformedIntervalStringException');
humbug_phpscoper_expose_class('ReflectionConstant', 'OtomatiesCoreVendor\ReflectionConstant');
humbug_phpscoper_expose_class('Deprecated', 'OtomatiesCoreVendor\Deprecated');
humbug_phpscoper_expose_class('NoDiscard', 'OtomatiesCoreVendor\NoDiscard');

// Function aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#function-aliases
if (!function_exists('app')) { function app() { return \OtomatiesCoreVendor\app(...func_get_args()); } }
if (!function_exists('append_config')) { function append_config() { return \OtomatiesCoreVendor\append_config(...func_get_args()); } }
if (!function_exists('array_all')) { function array_all() { return \OtomatiesCoreVendor\array_all(...func_get_args()); } }
if (!function_exists('array_any')) { function array_any() { return \OtomatiesCoreVendor\array_any(...func_get_args()); } }
if (!function_exists('array_find')) { function array_find() { return \OtomatiesCoreVendor\array_find(...func_get_args()); } }
if (!function_exists('array_find_key')) { function array_find_key() { return \OtomatiesCoreVendor\array_find_key(...func_get_args()); } }
if (!function_exists('array_first')) { function array_first() { return \OtomatiesCoreVendor\array_first(...func_get_args()); } }
if (!function_exists('array_last')) { function array_last() { return \OtomatiesCoreVendor\array_last(...func_get_args()); } }
if (!function_exists('bcdivmod')) { function bcdivmod() { return \OtomatiesCoreVendor\bcdivmod(...func_get_args()); } }
if (!function_exists('blank')) { function blank() { return \OtomatiesCoreVendor\blank(...func_get_args()); } }
if (!function_exists('calculateTranslationStatus')) { function calculateTranslationStatus() { return \OtomatiesCoreVendor\calculateTranslationStatus(...func_get_args()); } }
if (!function_exists('class_basename')) { function class_basename() { return \OtomatiesCoreVendor\class_basename(...func_get_args()); } }
if (!function_exists('class_uses_recursive')) { function class_uses_recursive() { return \OtomatiesCoreVendor\class_uses_recursive(...func_get_args()); } }
if (!function_exists('collect')) { function collect() { return \OtomatiesCoreVendor\collect(...func_get_args()); } }
if (!function_exists('data_fill')) { function data_fill() { return \OtomatiesCoreVendor\data_fill(...func_get_args()); } }
if (!function_exists('data_forget')) { function data_forget() { return \OtomatiesCoreVendor\data_forget(...func_get_args()); } }
if (!function_exists('data_get')) { function data_get() { return \OtomatiesCoreVendor\data_get(...func_get_args()); } }
if (!function_exists('data_has')) { function data_has() { return \OtomatiesCoreVendor\data_has(...func_get_args()); } }
if (!function_exists('data_set')) { function data_set() { return \OtomatiesCoreVendor\data_set(...func_get_args()); } }
if (!function_exists('e')) { function e() { return \OtomatiesCoreVendor\e(...func_get_args()); } }
if (!function_exists('env')) { function env() { return \OtomatiesCoreVendor\env(...func_get_args()); } }
if (!function_exists('extractLocaleFromFilePath')) { function extractLocaleFromFilePath() { return \OtomatiesCoreVendor\extractLocaleFromFilePath(...func_get_args()); } }
if (!function_exists('extractTranslationKeys')) { function extractTranslationKeys() { return \OtomatiesCoreVendor\extractTranslationKeys(...func_get_args()); } }
if (!function_exists('filled')) { function filled() { return \OtomatiesCoreVendor\filled(...func_get_args()); } }
if (!function_exists('findTransUnitMismatches')) { function findTransUnitMismatches() { return \OtomatiesCoreVendor\findTransUnitMismatches(...func_get_args()); } }
if (!function_exists('findTranslationFiles')) { function findTranslationFiles() { return \OtomatiesCoreVendor\findTranslationFiles(...func_get_args()); } }
if (!function_exists('fluent')) { function fluent() { return \OtomatiesCoreVendor\fluent(...func_get_args()); } }
if (!function_exists('fpow')) { function fpow() { return \OtomatiesCoreVendor\fpow(...func_get_args()); } }
if (!function_exists('getHtmlAttribute')) { function getHtmlAttribute() { return \OtomatiesCoreVendor\getHtmlAttribute(...func_get_args()); } }
if (!function_exists('getMaxHistoryMonthsByAmount')) { function getMaxHistoryMonthsByAmount() { return \OtomatiesCoreVendor\getMaxHistoryMonthsByAmount(...func_get_args()); } }
if (!function_exists('getOpenCollectiveSponsors')) { function getOpenCollectiveSponsors() { return \OtomatiesCoreVendor\getOpenCollectiveSponsors(...func_get_args()); } }
if (!function_exists('get_error_handler')) { function get_error_handler() { return \OtomatiesCoreVendor\get_error_handler(...func_get_args()); } }
if (!function_exists('get_exception_handler')) { function get_exception_handler() { return \OtomatiesCoreVendor\get_exception_handler(...func_get_args()); } }
if (!function_exists('grapheme_str_split')) { function grapheme_str_split() { return \OtomatiesCoreVendor\grapheme_str_split(...func_get_args()); } }
if (!function_exists('head')) { function head() { return \OtomatiesCoreVendor\head(...func_get_args()); } }
if (!function_exists('includeIfExists')) { function includeIfExists() { return \OtomatiesCoreVendor\includeIfExists(...func_get_args()); } }
if (!function_exists('isTranslationCompleted')) { function isTranslationCompleted() { return \OtomatiesCoreVendor\isTranslationCompleted(...func_get_args()); } }
if (!function_exists('json_validate')) { function json_validate() { return \OtomatiesCoreVendor\json_validate(...func_get_args()); } }
if (!function_exists('laravel_cloud')) { function laravel_cloud() { return \OtomatiesCoreVendor\laravel_cloud(...func_get_args()); } }
if (!function_exists('last')) { function last() { return \OtomatiesCoreVendor\last(...func_get_args()); } }
if (!function_exists('ldap_connect_wallet')) { function ldap_connect_wallet() { return \OtomatiesCoreVendor\ldap_connect_wallet(...func_get_args()); } }
if (!function_exists('ldap_exop_sync')) { function ldap_exop_sync() { return \OtomatiesCoreVendor\ldap_exop_sync(...func_get_args()); } }
if (!function_exists('literal')) { function literal() { return \OtomatiesCoreVendor\literal(...func_get_args()); } }
if (!function_exists('mb_check_encoding')) { function mb_check_encoding() { return \OtomatiesCoreVendor\mb_check_encoding(...func_get_args()); } }
if (!function_exists('mb_chr')) { function mb_chr() { return \OtomatiesCoreVendor\mb_chr(...func_get_args()); } }
if (!function_exists('mb_convert_case')) { function mb_convert_case() { return \OtomatiesCoreVendor\mb_convert_case(...func_get_args()); } }
if (!function_exists('mb_convert_encoding')) { function mb_convert_encoding() { return \OtomatiesCoreVendor\mb_convert_encoding(...func_get_args()); } }
if (!function_exists('mb_convert_variables')) { function mb_convert_variables() { return \OtomatiesCoreVendor\mb_convert_variables(...func_get_args()); } }
if (!function_exists('mb_decode_mimeheader')) { function mb_decode_mimeheader() { return \OtomatiesCoreVendor\mb_decode_mimeheader(...func_get_args()); } }
if (!function_exists('mb_decode_numericentity')) { function mb_decode_numericentity() { return \OtomatiesCoreVendor\mb_decode_numericentity(...func_get_args()); } }
if (!function_exists('mb_detect_encoding')) { function mb_detect_encoding() { return \OtomatiesCoreVendor\mb_detect_encoding(...func_get_args()); } }
if (!function_exists('mb_detect_order')) { function mb_detect_order() { return \OtomatiesCoreVendor\mb_detect_order(...func_get_args()); } }
if (!function_exists('mb_encode_mimeheader')) { function mb_encode_mimeheader() { return \OtomatiesCoreVendor\mb_encode_mimeheader(...func_get_args()); } }
if (!function_exists('mb_encode_numericentity')) { function mb_encode_numericentity() { return \OtomatiesCoreVendor\mb_encode_numericentity(...func_get_args()); } }
if (!function_exists('mb_encoding_aliases')) { function mb_encoding_aliases() { return \OtomatiesCoreVendor\mb_encoding_aliases(...func_get_args()); } }
if (!function_exists('mb_get_info')) { function mb_get_info() { return \OtomatiesCoreVendor\mb_get_info(...func_get_args()); } }
if (!function_exists('mb_http_input')) { function mb_http_input() { return \OtomatiesCoreVendor\mb_http_input(...func_get_args()); } }
if (!function_exists('mb_http_output')) { function mb_http_output() { return \OtomatiesCoreVendor\mb_http_output(...func_get_args()); } }
if (!function_exists('mb_internal_encoding')) { function mb_internal_encoding() { return \OtomatiesCoreVendor\mb_internal_encoding(...func_get_args()); } }
if (!function_exists('mb_language')) { function mb_language() { return \OtomatiesCoreVendor\mb_language(...func_get_args()); } }
if (!function_exists('mb_lcfirst')) { function mb_lcfirst() { return \OtomatiesCoreVendor\mb_lcfirst(...func_get_args()); } }
if (!function_exists('mb_list_encodings')) { function mb_list_encodings() { return \OtomatiesCoreVendor\mb_list_encodings(...func_get_args()); } }
if (!function_exists('mb_ltrim')) { function mb_ltrim() { return \OtomatiesCoreVendor\mb_ltrim(...func_get_args()); } }
if (!function_exists('mb_ord')) { function mb_ord() { return \OtomatiesCoreVendor\mb_ord(...func_get_args()); } }
if (!function_exists('mb_output_handler')) { function mb_output_handler() { return \OtomatiesCoreVendor\mb_output_handler(...func_get_args()); } }
if (!function_exists('mb_parse_str')) { function mb_parse_str() { return \OtomatiesCoreVendor\mb_parse_str(...func_get_args()); } }
if (!function_exists('mb_rtrim')) { function mb_rtrim() { return \OtomatiesCoreVendor\mb_rtrim(...func_get_args()); } }
if (!function_exists('mb_scrub')) { function mb_scrub() { return \OtomatiesCoreVendor\mb_scrub(...func_get_args()); } }
if (!function_exists('mb_str_pad')) { function mb_str_pad() { return \OtomatiesCoreVendor\mb_str_pad(...func_get_args()); } }
if (!function_exists('mb_str_split')) { function mb_str_split() { return \OtomatiesCoreVendor\mb_str_split(...func_get_args()); } }
if (!function_exists('mb_stripos')) { function mb_stripos() { return \OtomatiesCoreVendor\mb_stripos(...func_get_args()); } }
if (!function_exists('mb_stristr')) { function mb_stristr() { return \OtomatiesCoreVendor\mb_stristr(...func_get_args()); } }
if (!function_exists('mb_strlen')) { function mb_strlen() { return \OtomatiesCoreVendor\mb_strlen(...func_get_args()); } }
if (!function_exists('mb_strpos')) { function mb_strpos() { return \OtomatiesCoreVendor\mb_strpos(...func_get_args()); } }
if (!function_exists('mb_strrchr')) { function mb_strrchr() { return \OtomatiesCoreVendor\mb_strrchr(...func_get_args()); } }
if (!function_exists('mb_strrichr')) { function mb_strrichr() { return \OtomatiesCoreVendor\mb_strrichr(...func_get_args()); } }
if (!function_exists('mb_strripos')) { function mb_strripos() { return \OtomatiesCoreVendor\mb_strripos(...func_get_args()); } }
if (!function_exists('mb_strrpos')) { function mb_strrpos() { return \OtomatiesCoreVendor\mb_strrpos(...func_get_args()); } }
if (!function_exists('mb_strstr')) { function mb_strstr() { return \OtomatiesCoreVendor\mb_strstr(...func_get_args()); } }
if (!function_exists('mb_strtolower')) { function mb_strtolower() { return \OtomatiesCoreVendor\mb_strtolower(...func_get_args()); } }
if (!function_exists('mb_strtoupper')) { function mb_strtoupper() { return \OtomatiesCoreVendor\mb_strtoupper(...func_get_args()); } }
if (!function_exists('mb_strwidth')) { function mb_strwidth() { return \OtomatiesCoreVendor\mb_strwidth(...func_get_args()); } }
if (!function_exists('mb_substitute_character')) { function mb_substitute_character() { return \OtomatiesCoreVendor\mb_substitute_character(...func_get_args()); } }
if (!function_exists('mb_substr')) { function mb_substr() { return \OtomatiesCoreVendor\mb_substr(...func_get_args()); } }
if (!function_exists('mb_substr_count')) { function mb_substr_count() { return \OtomatiesCoreVendor\mb_substr_count(...func_get_args()); } }
if (!function_exists('mb_trim')) { function mb_trim() { return \OtomatiesCoreVendor\mb_trim(...func_get_args()); } }
if (!function_exists('mb_ucfirst')) { function mb_ucfirst() { return \OtomatiesCoreVendor\mb_ucfirst(...func_get_args()); } }
if (!function_exists('object_get')) { function object_get() { return \OtomatiesCoreVendor\object_get(...func_get_args()); } }
if (!function_exists('once')) { function once() { return \OtomatiesCoreVendor\once(...func_get_args()); } }
if (!function_exists('optional')) { function optional() { return \OtomatiesCoreVendor\optional(...func_get_args()); } }
if (!function_exists('preg_replace_array')) { function preg_replace_array() { return \OtomatiesCoreVendor\preg_replace_array(...func_get_args()); } }
if (!function_exists('printTable')) { function printTable() { return \OtomatiesCoreVendor\printTable(...func_get_args()); } }
if (!function_exists('printTitle')) { function printTitle() { return \OtomatiesCoreVendor\printTitle(...func_get_args()); } }
if (!function_exists('printTranslationStatus')) { function printTranslationStatus() { return \OtomatiesCoreVendor\printTranslationStatus(...func_get_args()); } }
if (!function_exists('retry')) { function retry() { return \OtomatiesCoreVendor\retry(...func_get_args()); } }
if (!function_exists('str')) { function str() { return \OtomatiesCoreVendor\str(...func_get_args()); } }
if (!function_exists('str_decrement')) { function str_decrement() { return \OtomatiesCoreVendor\str_decrement(...func_get_args()); } }
if (!function_exists('str_increment')) { function str_increment() { return \OtomatiesCoreVendor\str_increment(...func_get_args()); } }
if (!function_exists('stream_context_set_options')) { function stream_context_set_options() { return \OtomatiesCoreVendor\stream_context_set_options(...func_get_args()); } }
if (!function_exists('tap')) { function tap() { return \OtomatiesCoreVendor\tap(...func_get_args()); } }
if (!function_exists('textColorGreen')) { function textColorGreen() { return \OtomatiesCoreVendor\textColorGreen(...func_get_args()); } }
if (!function_exists('textColorNormal')) { function textColorNormal() { return \OtomatiesCoreVendor\textColorNormal(...func_get_args()); } }
if (!function_exists('textColorRed')) { function textColorRed() { return \OtomatiesCoreVendor\textColorRed(...func_get_args()); } }
if (!function_exists('throw_if')) { function throw_if() { return \OtomatiesCoreVendor\throw_if(...func_get_args()); } }
if (!function_exists('throw_unless')) { function throw_unless() { return \OtomatiesCoreVendor\throw_unless(...func_get_args()); } }
if (!function_exists('trait_uses_recursive')) { function trait_uses_recursive() { return \OtomatiesCoreVendor\trait_uses_recursive(...func_get_args()); } }
if (!function_exists('transform')) { function transform() { return \OtomatiesCoreVendor\transform(...func_get_args()); } }
if (!function_exists('trigger_deprecation')) { function trigger_deprecation() { return \OtomatiesCoreVendor\trigger_deprecation(...func_get_args()); } }
if (!function_exists('value')) { function value() { return \OtomatiesCoreVendor\value(...func_get_args()); } }
if (!function_exists('when')) { function when() { return \OtomatiesCoreVendor\when(...func_get_args()); } }
if (!function_exists('windows_os')) { function windows_os() { return \OtomatiesCoreVendor\windows_os(...func_get_args()); } }
if (!function_exists('with')) { function with() { return \OtomatiesCoreVendor\with(...func_get_args()); } }

return $loader;
