<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8a51cdc4960f1b398e83fcbbc41bcb0e
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '606a39d89246991a373564698c2d8383' => __DIR__ . '/..' . '/symfony/polyfill-php85/bootstrap.php',
        '662a729f963d39afe703c9d9b7ab4a8c' => __DIR__ . '/..' . '/symfony/polyfill-php83/bootstrap.php',
        '9d2b9fc6db0f153a0a149fefb182415e' => __DIR__ . '/..' . '/symfony/polyfill-php84/bootstrap.php',
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '23f09fe3194f8c2f70923f90d6702129' => __DIR__ . '/..' . '/illuminate/collections/functions.php',
        '60799491728b879e74601d83e38b2cad' => __DIR__ . '/..' . '/illuminate/collections/helpers.php',
        '2203a247e6fda86070a5e4e07aed533a' => __DIR__ . '/..' . '/symfony/clock/Resources/now.php',
        'a1105708a18b76903365ca1c4aa61b02' => __DIR__ . '/..' . '/symfony/translation/Resources/functions.php',
        'f625ee536139dfb962a398b200bdb2bd' => __DIR__ . '/..' . '/illuminate/support/functions.php',
        '72579e7bd17821bb1321b87411366eae' => __DIR__ . '/..' . '/illuminate/support/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'O' =>
        array (
            'OtomatiesCoreVendor\\voku\\' => 25,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php85\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php84\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php83\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Mbstring\\' => 46,
            'OtomatiesCoreVendor\\Symfony\\Contracts\\Translation\\' => 50,
            'OtomatiesCoreVendor\\Symfony\\Component\\Translation\\' => 50,
            'OtomatiesCoreVendor\\Symfony\\Component\\Clock\\' => 44,
            'OtomatiesCoreVendor\\Psr\\SimpleCache\\' => 36,
            'OtomatiesCoreVendor\\Psr\\Container\\' => 34,
            'OtomatiesCoreVendor\\Psr\\Clock\\' => 30,
            'OtomatiesCoreVendor\\Otomaties\\Core\\' => 35,
            'OtomatiesCoreVendor\\Illuminate\\Support\\' => 39,
            'OtomatiesCoreVendor\\Illuminate\\Contracts\\' => 41,
            'OtomatiesCoreVendor\\Illuminate\\Container\\' => 41,
            'OtomatiesCoreVendor\\Illuminate\\Config\\' => 38,
            'OtomatiesCoreVendor\\Doctrine\\Inflector\\' => 39,
            'OtomatiesCoreVendor\\Composer\\Installers\\' => 40,
            'OtomatiesCoreVendor\\Carbon\\Doctrine\\' => 36,
            'OtomatiesCoreVendor\\Carbon\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OtomatiesCoreVendor\\voku\\' =>
        array (
            0 => __DIR__ . '/..' . '/voku/portable-ascii/src/voku',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php85\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php85',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php84\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php84',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php83\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php83',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Mbstring\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'OtomatiesCoreVendor\\Symfony\\Contracts\\Translation\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'OtomatiesCoreVendor\\Symfony\\Component\\Translation\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'OtomatiesCoreVendor\\Symfony\\Component\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/clock',
        ),
        'OtomatiesCoreVendor\\Psr\\SimpleCache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'OtomatiesCoreVendor\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'OtomatiesCoreVendor\\Psr\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'OtomatiesCoreVendor\\Otomaties\\Core\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Support\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/support',
            1 => __DIR__ . '/..' . '/illuminate/collections',
            2 => __DIR__ . '/..' . '/illuminate/macroable',
            3 => __DIR__ . '/..' . '/illuminate/conditionable',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Contracts\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/container',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Config\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/config',
        ),
        'OtomatiesCoreVendor\\Doctrine\\Inflector\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/src',
        ),
        'OtomatiesCoreVendor\\Composer\\Installers\\' =>
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'OtomatiesCoreVendor\\Carbon\\Doctrine\\' =>
        array (
            0 => __DIR__ . '/..' . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine',
        ),
        'OtomatiesCoreVendor\\Carbon\\' =>
        array (
            0 => __DIR__ . '/..' . '/nesbot/carbon/src/Carbon',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OtomatiesCoreVendor\\DateError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
        'OtomatiesCoreVendor\\DateException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
        'OtomatiesCoreVendor\\DateInvalidOperationException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
        'OtomatiesCoreVendor\\DateInvalidTimeZoneException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
        'OtomatiesCoreVendor\\DateMalformedIntervalStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
        'OtomatiesCoreVendor\\DateMalformedPeriodStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
        'OtomatiesCoreVendor\\DateMalformedStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
        'OtomatiesCoreVendor\\DateObjectError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
        'OtomatiesCoreVendor\\DateRangeError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
        'OtomatiesCoreVendor\\Deprecated' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
        'OtomatiesCoreVendor\\NoDiscard' => __DIR__ . '/..' . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
        'OtomatiesCoreVendor\\Override' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/Override.php',
        'OtomatiesCoreVendor\\ReflectionConstant' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
        'OtomatiesCoreVendor\\SQLite3Exception' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8a51cdc4960f1b398e83fcbbc41bcb0e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8a51cdc4960f1b398e83fcbbc41bcb0e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8a51cdc4960f1b398e83fcbbc41bcb0e::$classMap;

        }, null, ClassLoader::class);
    }
}
