<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7659bd63f0b3f1368e7a318e56df8608
{
    public static $files = array (
        '43dbc81e0b6135b102f4ee8672dfef5d' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '22e44187963ed9e3ad191181f1ee740e' => __DIR__ . '/..' . '/symfony/polyfill-php85/bootstrap.php',
        '2c542aca3a5082dfa8e429b588c69142' => __DIR__ . '/..' . '/symfony/polyfill-php83/bootstrap.php',
        'fd195c0cc03b28ca6071d9101d8f9dfd' => __DIR__ . '/..' . '/symfony/polyfill-php84/bootstrap.php',
        '68be21903f0c6a14e55d7be30606b578' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        'daf78f8ec7f5e3964d38afa65951c87e' => __DIR__ . '/..' . '/illuminate/collections/functions.php',
        '05088ca19eb1fc3f06a41e92c68a2c80' => __DIR__ . '/..' . '/illuminate/collections/helpers.php',
        '062cbcb23836576b715d71c207e40342' => __DIR__ . '/..' . '/symfony/clock/Resources/now.php',
        '1ced0ba83f1a24d831a017c0731230a6' => __DIR__ . '/..' . '/symfony/translation/Resources/functions.php',
        '33f7b882e202b5831ae6db34f1cd37c3' => __DIR__ . '/..' . '/illuminate/support/functions.php',
        'c6983a83d3d2b6d3190ee8df8781807a' => __DIR__ . '/..' . '/illuminate/support/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'O' =>
        array (
            'OtomatiesCoreVendor\\voku\\' => 25,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php85\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php84\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php83\\' => 43,
            'OtomatiesCoreVendor\\Symfony\\Polyfill\\Mbstring\\' => 46,
            'OtomatiesCoreVendor\\Symfony\\Contracts\\Translation\\' => 50,
            'OtomatiesCoreVendor\\Symfony\\Component\\Translation\\' => 50,
            'OtomatiesCoreVendor\\Symfony\\Component\\Clock\\' => 44,
            'OtomatiesCoreVendor\\Psr\\SimpleCache\\' => 36,
            'OtomatiesCoreVendor\\Psr\\Container\\' => 34,
            'OtomatiesCoreVendor\\Psr\\Clock\\' => 30,
            'OtomatiesCoreVendor\\Otomaties\\Core\\' => 35,
            'OtomatiesCoreVendor\\Illuminate\\Support\\' => 39,
            'OtomatiesCoreVendor\\Illuminate\\Contracts\\' => 41,
            'OtomatiesCoreVendor\\Illuminate\\Container\\' => 41,
            'OtomatiesCoreVendor\\Illuminate\\Config\\' => 38,
            'OtomatiesCoreVendor\\Doctrine\\Inflector\\' => 39,
            'OtomatiesCoreVendor\\Composer\\Installers\\' => 40,
            'OtomatiesCoreVendor\\Carbon\\Doctrine\\' => 36,
            'OtomatiesCoreVendor\\Carbon\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OtomatiesCoreVendor\\voku\\' =>
        array (
            0 => __DIR__ . '/..' . '/voku/portable-ascii/src/voku',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php85\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php85',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php84\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php84',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Php83\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php83',
        ),
        'OtomatiesCoreVendor\\Symfony\\Polyfill\\Mbstring\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'OtomatiesCoreVendor\\Symfony\\Contracts\\Translation\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'OtomatiesCoreVendor\\Symfony\\Component\\Translation\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'OtomatiesCoreVendor\\Symfony\\Component\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/clock',
        ),
        'OtomatiesCoreVendor\\Psr\\SimpleCache\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'OtomatiesCoreVendor\\Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'OtomatiesCoreVendor\\Psr\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'OtomatiesCoreVendor\\Otomaties\\Core\\' =>
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Support\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/support',
            1 => __DIR__ . '/..' . '/illuminate/collections',
            2 => __DIR__ . '/..' . '/illuminate/macroable',
            3 => __DIR__ . '/..' . '/illuminate/conditionable',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Contracts\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/container',
        ),
        'OtomatiesCoreVendor\\Illuminate\\Config\\' =>
        array (
            0 => __DIR__ . '/..' . '/illuminate/config',
        ),
        'OtomatiesCoreVendor\\Doctrine\\Inflector\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/src',
        ),
        'OtomatiesCoreVendor\\Composer\\Installers\\' =>
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
        'OtomatiesCoreVendor\\Carbon\\Doctrine\\' =>
        array (
            0 => __DIR__ . '/..' . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine',
        ),
        'OtomatiesCoreVendor\\Carbon\\' =>
        array (
            0 => __DIR__ . '/..' . '/nesbot/carbon/src/Carbon',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'OtomatiesCoreVendor\\DateError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
        'OtomatiesCoreVendor\\DateException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
        'OtomatiesCoreVendor\\DateInvalidOperationException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
        'OtomatiesCoreVendor\\DateInvalidTimeZoneException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
        'OtomatiesCoreVendor\\DateMalformedIntervalStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
        'OtomatiesCoreVendor\\DateMalformedPeriodStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
        'OtomatiesCoreVendor\\DateMalformedStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
        'OtomatiesCoreVendor\\DateObjectError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
        'OtomatiesCoreVendor\\DateRangeError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
        'OtomatiesCoreVendor\\Deprecated' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
        'OtomatiesCoreVendor\\NoDiscard' => __DIR__ . '/..' . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
        'OtomatiesCoreVendor\\Override' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/Override.php',
        'OtomatiesCoreVendor\\ReflectionConstant' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
        'OtomatiesCoreVendor\\SQLite3Exception' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7659bd63f0b3f1368e7a318e56df8608::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7659bd63f0b3f1368e7a318e56df8608::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7659bd63f0b3f1368e7a318e56df8608::$classMap;

        }, null, ClassLoader::class);
    }
}
