<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Php85\\' => array($vendorDir . '/symfony/polyfill-php85'),
    'Symfony\\Polyfill\\Php84\\' => array($vendorDir . '/symfony/polyfill-php84'),
    'Symfony\\Polyfill\\Php83\\' => array($vendorDir . '/symfony/polyfill-php83'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Otomaties\\Core\\' => array($baseDir . '/app'),
    'OtomatiesCoreVendor\\voku\\' => array($vendorDir . '/voku/portable-ascii/src/voku'),
    'OtomatiesCoreVendor\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'OtomatiesCoreVendor\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'OtomatiesCoreVendor\\Symfony\\Component\\Clock\\' => array($vendorDir . '/symfony/clock'),
    'OtomatiesCoreVendor\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'OtomatiesCoreVendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'OtomatiesCoreVendor\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'OtomatiesCoreVendor\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/support', $vendorDir . '/illuminate/reflection', $vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/macroable', $vendorDir . '/illuminate/conditionable'),
    'OtomatiesCoreVendor\\Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'OtomatiesCoreVendor\\Illuminate\\Container\\' => array($vendorDir . '/illuminate/container'),
    'OtomatiesCoreVendor\\Illuminate\\Config\\' => array($vendorDir . '/illuminate/config'),
    'OtomatiesCoreVendor\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/src'),
    'OtomatiesCoreVendor\\Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'OtomatiesCoreVendor\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'OtomatiesCoreVendor\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
);
