<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'OtomatiesCoreVendor\\DateError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
    'OtomatiesCoreVendor\\DateException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
    'OtomatiesCoreVendor\\DateInvalidOperationException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
    'OtomatiesCoreVendor\\DateInvalidTimeZoneException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
    'OtomatiesCoreVendor\\DateMalformedIntervalStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
    'OtomatiesCoreVendor\\DateMalformedPeriodStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
    'OtomatiesCoreVendor\\DateMalformedStringException' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
    'OtomatiesCoreVendor\\DateObjectError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
    'OtomatiesCoreVendor\\DateRangeError' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
    'OtomatiesCoreVendor\\Deprecated' => $vendorDir . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
    'OtomatiesCoreVendor\\NoDiscard' => $vendorDir . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
    'OtomatiesCoreVendor\\Override' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/Override.php',
    'OtomatiesCoreVendor\\ReflectionConstant' => $vendorDir . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
    'OtomatiesCoreVendor\\SQLite3Exception' => $vendorDir . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
);
